### ISSUE TITLE
byte,error,chinese

### ISSUE THREAD

**Issue by typ431127** [mick88/samp-client#10]
Hello, an error will be reported when the game mode is Chinese

return string[len_end:len_end + length].decode('utf-8')

> Traceback (most recent call last):
  File "D:/aliyun_code/js/python/game_api/sa-mp/sa.py", line 9, in <module>
    print(client.get_server_info())
  File "D:\apps\pyhon3\lib\site-packages\samp_client\client.py", line 68, in get_server_info
    hostname = decode_string(response, 5, 4)
  File "D:\apps\pyhon3\lib\site-packages\samp_client\utils.py", line 66, in decode_string
    return string[len_end:len_end + length].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte

**Comment by typ431127** [comment]
ip:118.25.92.102
port:7777

**Comment by mick88** [comment]
Sorry, but the server listed does not appear to be online. Can you please paste the gamemode name here?
Or write a test case against this issue? A PR would be most welcome if you manage to fix it.

**Comment by typ431127** [comment]
I removed the utils.py file.decode('utf-8'), I used gb212 to decode successfully, thank you, the problem has been solved.
`    def get_server_info(self):
        try:

            with SampClient(address=address, port=port) as client:
                data = client.get_server_info()
                data_client = client.get_server_clients_detailed()
                server_list = {}
                list = []
                for i in data_client:
                    a = {}
                    a['name'] = i.name.decode(encoding='gb2312')
                    a['score'] = i.score
                    a['ping'] = i.ping
                    list.append(a)
                server_list['response'] = list
                return True,data,server_list

        except Exception :

            return False,False,False`

**Comment by mick88** [comment]
I think this is related to #11 which has been resolved by updating encoding to cp1252 - I think it's the correct encoding.
Please let me know if the problem persists with the corrected encoding.
