### ISSUE TITLE
Player's ingame id

### ISSUE THREAD

**Issue by tpbotecrpg** [mick88/samp-client#24]
id = []
        name = []
        score = []
        ping = []
        data = ""
        data2 = ""
        data3 = ""
        data4 = ""
        data5 = ""
        data6 = ""
        data7 = ""
        address = self.serverlist[num-1]["address"]
        port = self.serverlist[num-1]["port"]
        info, clients, rules = self.loadserver(address, port)
        for client in clients:
            cid = str(client.id)
            cname = str(client.name)
            cscore = str(client.score)
            cping = str(client.ping)
            id.append(cid)
            name.append(cname)
            score.append(cscore)
            ping.append(cping)
        for x,y in enumerate(name):
            if x <= 9:
                data += f"**__ID:__** {id[x]} | **__Name:__** {name[x]} | **__Score:__** {score[x]} | **__Ping:__** {ping[x]}\n"
            elif x <= 19:
                data2 += f"**__ID:__** {id[x]} | **__Name:__** {name[x]} | **__Score:__** {score[x]} | **__Ping:__** {ping[x]}\n"
            elif x <= 29:
                data3 += f"**__ID:__** {id[x]} | **__Name:__** {name[x]} | **__Score:__** {score[x]} | **__Ping:__** {ping[x]}\n"
            elif x <= 39:
                data4 += f"**__ID:__** {id[x]} | **__Name:__** {name[x]} | **__Score:__** {score[x]} | **__Ping:__** {ping[x]}\n"
            elif x <= 49:
                data5 += f"**__ID:__** {id[x]} | **__Name:__** {name[x]} | **__Score:__** {score[x]} | **__Ping:__** {ping[x]}\n"
            elif x <= 59:
                data6 += f"**__ID:__** {id[x]} | **__Name:__** {name[x]} | **__Score:__** {score[x]} | **__Ping:__** {ping[x]}\n"
            else:
                data7 += f"**__ID:__** {id[x]} | **__Name:__** {name[x]} | **__Score:__** {score[x]} | **__Ping:__** {ping[x]}\n"

I have this code, the id in this returns as 0 only whn it should return as  0, 1 ,2 , 3 ... 
Attaching an output image
![Screenshot_20210502-182009](https://user-images.githubusercontent.com/81532200/116836764-7395f500-abe5-11eb-9d31-2f4dc15352fc.png)

**Comment by ryuuzu** [comment]
I think I fixed it. The offset wasn't added properly. It was pretty easy fix lol.
```Python
def get_server_clients_detailed(self):
        response = self.send_request(OPCODE_CLIENTS_DETAILED)
        result = []
        if response is None:
            # SA-MP server will return null if there's a lot of players
            # We'll handle this by returning an empty list instead to avoid type error.
            return result
        num_clients = decode_int(response[:2])
        offset = 2
        for n in range(num_clients):
            player_id = decode_int(response[offset:offset + 1]) #I just added a "+ 1" here
            offset += 1
            name = decode_string(response, offset, len_bytes=1)
            offset += 1 + len(name)
            score = decode_int(response[offset:offset + 4])
            offset += 4
            ping = decode_int(response[offset:offset + 4])
            offset += 4
            detail = ClientDetail(
                id=player_id,
                name=name,
                score=score,
                ping=ping,
            )
            result.append(detail)
        return result```
