### ISSUE TITLE
Extra features using requests module

### ISSUE THREAD

**Issue by DeViL252** [mick88/samp-client#25]
I am using this module for discord bots there is a few drawbacks like putting the whole IP and port, this is little bit annoying because if you want to know any other server info, like some users wanted to know players info of others server aswell and then i think to make a database and add there server ip and port there so for the next time they do not have to copy paste ip and port. Now, i'm think what happen if use requests module to fetch all other servers aswell from a site like open.mp [https://open.mp/servers](url). so that we can easily search the server as per the requirement???

**Comment by mick88** [comment]
This is a client for samp protocol connecting to outside server falls outside of scope for this project.
